### PR TITLE
Parse group name and use it for generation

### LINKED ISSUE #39: informers: apiserverinternal storageversions.go is incorrect
Have:
```go
func NewFilteredStorageVersionInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiserverinternalV1alpha1().StorageVersions().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiserverinternalV1alpha1().StorageVersions().Watch(context.TODO(), options)
			},
		},
		&apiserverinternalv1alpha1.StorageVersion{},
		resyncPeriod,
		indexers,
	)
}
```

where `client versioned.Interface` is k8s.io/client-go/kubernetes.Interface
```go
type Interface interface {
	Discovery() discovery.DiscoveryInterface
	AdmissionregistrationV1() admissionregistrationv1.AdmissionregistrationV1Interface
	AdmissionregistrationV1beta1() admissionregistrationv1beta1.AdmissionregistrationV1beta1Interface
	InternalV1alpha1() internalv1alpha1.InternalV1alpha1Interface
        // ...
```

Inside ListFunc and WatchFunc it needs to be `client.InternalV1alpha1().StorageVersions()....`

### PR DESCRIPTION
**Pull request by fabianvf**
closes #39

### CODE REVIEW

File: pkg/generators/informergen/informergen.go [hunk 1]
```diff
@@ -213,6 +225,11 @@ func (g *Generator) GetGVKs(ctx *genall.GenerationContext) (map[types.Group]map[
 		}
 	}
 
+	for oldGroupName, newGroupName := range renamedGroups {
+		gvks[newGroupName] = gvks[oldGroupName]
+		delete(gvks, oldGroupName)
```
Comment (fabianvf) [inline pkg/generators/informergen/informergen.go:230]: so this generates the proper calls but messes up the import paths. Need to store the GoName in addition to the import name. Probably will make a wrapper around types.Group that includes this info.

**Comment by fabianvf** [comment]
Tests failing because clientgen doesn't support GroupName, might make sense to wait for #35
